"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.5.
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

AUTH_USER_MODEL = 'vPanelDBapp.User'

# Quick-start development settings which are unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
# Security: keep the production secret key secret

SECRET_KEY = 'jf8hds&gjrvskr1o%4qt$*9x47dh5nzk_)kw5ukb15am2e1(=6'

DEBUG = True  # Don't run with debug on in the user version

ALLOWED_HOSTS = ['127.0.0.1', 'callum.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vPanelDBapp',
    'django_extensions',
    'easy_select2',
    'django_select2',
    'djangobower',
]

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static_files", "our_static"),)
LOGIN_REDIRECT_URL = '/login/'
LOGOUT_URL = '/logout/'

#  Bower add-ons

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
)
BOWER_COMPONENTS_ROOT = '/PROJECT_ROOT/components/'
BOWER_PATH = '/usr/bin/bower'
BOWER_INSTALLED_APPS = (
    'select2',
)

# Language/Timezone

LANGUAGE_CODE = 'en-GB'
TIME_ZONE = 'Europe/London'

# Other javascript bits

USE_DJANGO_JQUERY = True
JQUERY_URL = False