# Generated by Django 2.0 on 2020-02-27 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=80)),
                ('age_field', models.PositiveIntegerField()),
                ('is_proband', models.CharField(max_length=80)),
                ('aff_relative', models.CharField(max_length=80)),
                ('stage_field', models.PositiveIntegerField()),
                ('desc_field', models.CharField(max_length=80)),
                ('sequencer', models.CharField(max_length=80)),
                ('variant_cDNA', models.CharField(max_length=80)),
                ('variant_protein', models.CharField(max_length=80)),
                ('variant_genome', models.CharField(max_length=80)),
                ('pathogenicity_code', models.CharField(max_length=80)),
                ('evidence', models.CharField(max_length=80)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
