# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170922_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='moretext',
            field=models.NullBooleanField(),
        ),
    ]
