# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vPanelDBapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeneName', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PanelName', models.CharField(max_length=30, unique=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='moretext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='Panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vPanelDBapp.Panel'),
        ),
    ]
