# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vPanelDBapp', '0003_auto_20170922_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='moretext',
            new_name='subpanels',
        ),
    ]
