# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vPanelDBapp', '0004_auto_20170922_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='genes',
        ),
    ]
