# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vPanelDBapp', '0005_auto_20170922_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Panel_Name',
        ),
    ]
