# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vPanelDBapp', '0006_auto_20170922_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='transcripts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
