# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vPanelDBapp', '0009_newgene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_ID', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newgene',
            name='Test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vPanelDBapp.Test'),
        ),
    ]
